name: Integracion con develop
on:
  push:
    branches: [ main ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Prueba dos
      env:
        Mensaje: ${{ github.ref }}
      run: echo ${Mensaje}
      
