name: Pruebas unitarias
on:
  push
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Integracion con rama develop
      if: ${{ contains( github.ref , 'feature' ) }}
      env:
        NombreRama: ${{ github.ref }}
      run: echo "Hizo Push en la rama feature"
      
    - name: Integracion con rama release
      if: ${{ contains( github.ref , 'develop' ) }}
      env:
        NombreRama: ${{ github.ref }}
      run: echo "Hizo Push en la rama develop"
