name: Integracion con develop
on:
  push
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Prueba dos
      if: ${{ contains( github.ref , 'Ma' ) }}
      env:
        Mensaje: ${{ github.ref }}
      run: 
        echo ${Mensaje}
      
