name: Pruebas unitarias
on:
  push
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.RamaDevelop.outputs.respuesta }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
          
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Integracion con rama develop
      id: RamaDevelop
      if: ${{ (contains( github.ref , 'feature' )) && (contains( github.event.head_commit.message , 'DEV:')) }}
      env:
        VARIABLE: "ContinuarDevelop"
      run: echo "::set-output name=respuesta::${VARIABLE}"
      
  job2:
    needs: job1
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Correr pruebas
      id: correr-pruebas
      if: ${{ (contains( needs.job1.outputs.salida , 'ContinuarDevelop' )) }}
      run: python -m unittest -v tests/test_prueba.py
      
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "${MENSAJE_ERROR}"
      
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "${MENSAJE_EXITO}"


